Internal Server Error: /api/v1/status/2
Traceback (most recent call last):
  File "/home/pearlsoft/.local/share/virtualenvs/hrm-Fz0GWP2y/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/pearlsoft/.local/share/virtualenvs/hrm-Fz0GWP2y/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pearlsoft/.local/share/virtualenvs/hrm-Fz0GWP2y/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/pearlsoft/.local/share/virtualenvs/hrm-Fz0GWP2y/lib/python3.8/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/pearlsoft/.local/share/virtualenvs/hrm-Fz0GWP2y/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/pearlsoft/.local/share/virtualenvs/hrm-Fz0GWP2y/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/pearlsoft/.local/share/virtualenvs/hrm-Fz0GWP2y/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/pearlsoft/.local/share/virtualenvs/hrm-Fz0GWP2y/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/pearlsoft/Desktop/hrm/hrmapp/views.py", line 107, in get
    leave_obj=Leave.objects.get(user=user_obj)
  File "/home/pearlsoft/.local/share/virtualenvs/hrm-Fz0GWP2y/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/pearlsoft/.local/share/virtualenvs/hrm-Fz0GWP2y/lib/python3.8/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
hrmapp.models.Leave.DoesNotExist: Leave matching query does not exist.
"GET /api/v1/status/2 HTTP/1.1" 500 104735
